# Generated by Django 3.0.2 on 2020-01-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0009_auto_20200121_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
